title: The Rock n' roll website
author: Devraj Hazarika
email: dhlodestar@github.com
description: > # this means to ignore newlines until "baseurl:"
  The website dedictaed the kings of rock n roll and how we can do lots of things with it. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
